CapabilityInterface capability
string node_id
string mission_control_name
---
# result
bool success
string error_message
bool execute_local
string executor_mission_control_topic
string implementation_name
float64 max_allowed_costs
