string parent_name
Node node
# If this is true, rename the node to name_N if one or more
# nodes with the same name / prefix exist already.
bool allow_rename
---
bool success
string actual_node_name
string error_message
