# file:// or package:// URIs that point to folders containing Tree
# YAML files
string[] subtree_paths
---
# Provide subtree nodes instead of tree objects here, because if we're
# planning on using them as building blocks in another tree, that's
# the form we need them in.
Node[] available_subtree_nodes
bool success
string error_message
