## Move a Node from its current position to be a child of the node at
## new_parent_name. new_child_index determines the Node's index in
## the new parent's children array.
string node_name
string new_parent_name
# Follows Python convention, i.e. can be negative to count from the
# end of the children list.
int32 new_child_index
---
bool success
string error_message
