# goal
CapabilityInterface capability
---
# result
bool success
string error_message
Tree implementation_tree
string input_announcement_topic
string output_announcement_topic
---
# feedback
string[] queried_mission_controllers
