# goal
CapabilityInterface capability
---
# result
bool success
string error_message
bool execute_local
string implementation_name
string remote_mission_controller_topic
---
# feedback
float64 progress
string message
