# goal
CapabilityInterface capability
---
# result
bool success
string error_message
string executor_mission_control_topic
string implementation_uuid
---
# feedback
string[] queried_mission_controllers
