## Run the given tree (with the given set of inputs) until it
## succeeds or fails.
##
## Be aware that you cannot change the inputs on each tick like you
## could with the service interface!

#goal definition
Tree tree
float64 tick_frequency_hz
---
#result definition
Tree final_tree
---
#feedback
Tree current_tree
